inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "support/**/*"
    - "google-cloud-spanner.gemspec"
    - "Rakefile"
    - "test/**/*"
    - "benchmark/**/*"
    - "vendor/**/*"
    - "acceptance/data/protos/**/*"

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "acceptance/**/*"
    - ".toys.rb"
Metrics/MethodLength:
  Exclude:
    - "acceptance/**/*"
Metrics/ModuleLength:
  Exclude:
    - "acceptance/**/*"
Metrics/AbcSize:  
  Exclude:
      - "acceptance/**/*"  
      - "lib/google/cloud/spanner/interval.rb"
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - "acceptance/**/*"
    - "lib/google/cloud/spanner.rb"
    - "lib/google/cloud/spanner/interval.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "acceptance/**/*"
    - "lib/google/cloud/spanner.rb"
    - "lib/google/cloud/spanner/interval.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-spanner.rb"
Style/GlobalVars:   
  Exclude:
      - "acceptance/**/*"
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
