source "https://rubygems.org"

gemspec

gem "autotest-suffix", "~> 1.1"
gem "gapic-common", ">= 0.25.0"
gem "google-cloud-core", "~> 1.8.0"
gem "google-cloud-errors", "~> 1.5.0"
gem "google-cloud-spanner-admin-database-v1", "~> 1.3"
gem "google-cloud-spanner-admin-instance-v1", "~> 1.5"
gem "google-cloud-spanner-v1", "~> 1.8"
gem "google-style", "~> 1.31.0"
gem "grpc", "~> 1.67"
gem "grpc-tools", "~> 1.74", ">= 1.74.1"
gem "minitest", "~> 5.25"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.4"
gem "minitest-rg", "~> 5.3"
gem "pry", group: :development, require: false
gem "rake"
gem "redcarpet", "~> 3.0"
gem "simplecov", "~> 0.22"
gem "solargraph", group: :development, require: false
gem "yard", "~> 0.9"
gem "yard-doctest", "~> 0.1.17", group: :development
