name: Run Spanner integration tests against service emulator

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'google-cloud-spanner*/**'
  pull_request:
    paths:
      - 'google-cloud-spanner*/**'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: google-cloud-spanner

    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:1.5.50
        ports:
          - 9010:9010
          - 9020:9020

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: '4.0.5'
      - run: ruby --version
      - run: bundle install
      - run: bundle exec rake acceptance
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_TEST_PROJECT: emulator-test-project
          MT_COMPAT: true
